<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h2>User Login</h2>

    <!-- <h5>Login using this form</h5> -->


<?php echo $this->tag->form("login/loginUser"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <p>
        <label for="rememberme">
            <?php echo $this->tag->checkField(["rememberme", "value"=>"1"]); ?> 
            &nbsp;&nbsp;&nbsp; Remember me
        </label>
        
    </p>

    <p>
        <?php echo $this->tag->submitButton("Login"); ?>
    </p>

</form>
</body>
</html>