<?php

    // echo "<pre>";
    // print_r($response);
    foreach($response as $k => $value)
    {
        $bib_key = $value->bib_key;
        $info_url = $value->info_url;
        $preview_url = $value->preview_url;
        $thumbnail_url = $value->thumbnail_url;

        $publishers = $value->details->publishers[0] ;
        $last_modified = $value->details->last_modified->value ;
        $title = $value->details->title ;
        $full_title = $value->details->full_title ;
        $publish_date = $value->details->publish_date ;
        $author = $value->details->authors[0]->name ;
        $latest_revision = $value->details->latest_revision ;

    }


    // print_r($publishers);
 ?>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container bg-secondary">
    <div class="card text-white bg-dark">
        <div class="card-body text-white ">
            <h2 class="card-title"><?= $full_title ?></h2>
            <!-- <h6 class="card-subtitle">globe type chair for rest</h6> -->
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center"><a href=<?= $thumbnail_url ?>><img src=<?= $thumbnail_url ?> class="img-responsive"></a></div>
                </div>
                <!-- <div class="col-lg-7 col-md-7 col-sm-6">
                    
                </div> -->










                <div class="col-lg-12 col-md-12 col-sm-12 text-white">
                    <h3 class="box-title mt-5">General Info</h3>
                    <div class="table-responsive text-white">
                        <table class="table table-striped table-dark table-hover text-white">
                            <tbody>
                                <tr>
                                    <td width="390">BIB ID</td>
                                    <td><?= $bib_key ?></td>
                                </tr>
                                <tr>
                                    <td>TITLE</td>
                                    <td><?= $full_title ?></td>
                                </tr>
                                <tr>
                                    <td>PUBLISH DATE</td>
                                    <td><?= $publish_date ?></td>
                                </tr>
                                <tr>
                                    <td>AUTHOR</td>
                                    <td><?= $author ?></td>
                                </tr>
                                <tr>
                                    <td>LATEST REVISION</td>
                                    <td><?= $latest_revision ?></td>
                                </tr>
                                <tr>
                                    <td>INFO URL</td>
                                    <td><a href=<?= $info_url ?>><?= $info_url ?></a></td>
                                </tr>
                               
                                <tr>
                                    <td>PREVIEW URL</td>
                                    <td><a href=<?= $preview_url ?>><?= $preview_url ?></a></td>
                                </tr>
                                <tr>
                                    <td>PUBLISHERS</td>
                                    <td><?= $publishers ?></td>
                                </tr>
                                <tr>
                                    <td>LAST MODIFIED</td>
                                    <td><?= $last_modified ?></td>
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>









<!-- <br>-------------------------------------------------------------------------------------------------------------<br> -->

