<?php
// echo $this->session->exists().' hey \n';/
echo "<h1>Hello World</h1>";

echo PHP_EOL;

echo '<br>';

echo $this->tag->linkTo(
    'apiCheck',
    'Check or Test for API!'
);


echo '<br>';
?>
<br><br>

<h3>Search for books from openlibrary.org</h3><br>

<?php echo $this->tag->form("index/searchBook"); ?>
    <p>
        <label for="search">Search : </label>
        <?php echo $this->tag->textField("search"); ?>

    </p>

    <p>
        <?php echo $this->tag->submitButton("Search"); ?>
    </p>
</form>