<?php
// echo "<pre>";
// print_r($urlFmt);
    
$num = $response->numFound;
$bookList = $response->docs;
// print_r($bookList);
// if(isset(  )) { }
?>

<!-- <div class="card-columns"> -->

<?php

for ($x = 0; $x < $num; $x++) {
    if(isset( $bookList[$x]->isbn )) {
        $isbnCount = count($bookList[$x]->isbn);
        $latestIsbn = $bookList[$x]->isbn[$isbnCount - 1];
    }
?>


    <div class="card mb-3" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <a href="bookDescription?isbn=<?= $latestIsbn ?>">
                    <img src="//covers.openlibrary.org/b/olid/<?= $bookList[$x]->lending_edition_s ?>-M.jpg" class="card-img-top" alt="Cover of <?= $bookList[$x]->title ?> ">
                </a>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title"><?= $bookList[$x]->title ?></h5>
                    <!-- <p class="card card-text"> <h3> </h3>  </p> -->
                    <p class="card card-text"> by <b><?= $bookList[$x]->author_name[0] ?> </b>  </p>
                    <p class="card card-text"> First published in <?= $bookList[$x]->first_publish_year ?> </p>
                    <p class="card-text"> <?= $bookList[$x]->edition_count ?> <?php if ($bookList[$x]->edition_count == 1){ ?> edition <?php } else {?> editions <?php } if(isset($bookList[$x]->ia_box_id)) { ?> --- <?= count($bookList[$x]->ia_box_id); ?> previewable</p> <?php } ?>
                    <a href="https://www.google.co.in/books/edition/<?= $urlFmt ?>/<?= $bookList[$x]->id_google[0] ?>?hl=en " class="btn btn-primary">Google Link</a>
                    <a href="https://www.google.co.in/books/edition/<?= $urlFmt ?>/<?= $bookList[$x]->id_amazon[0] ?>?hl=en " class="btn btn-primary">Amazon Link</a>
                    
                </div>
            </div>
        </div>
    </div>




<?php
    } 
    
?>
<!-- </div> -->