<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>


    <?php 

        if($this->session->has('name')){

            // echo isset($this->session->name).' hey ';

            // echo '&nbsp;';
            $name = $this->session->name;
            echo '<h2>Hello '.$name.'!</h2>';

    ?>

    <p>
        
        <?php echo $this->tag->linkTo(
                [
                    'index/logout',
                    'Logout',
                    'class' => 'logoutBtn',
                ]
            ); 

        } else {
            echo '<h3>Please Login!</h3>';
            

            echo $this->tag->linkTo(
                'login',
                'Login Here!'
            );
        }
        ?>
    </p>
</body>
</html>